version: "3"
services:
  pg:
    image: "postgres:latest"
    container_name: "pg-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    volumes:
      - /var/lib/postgresql/data
